#!/usr/bin/python


#ProNser
import os
import argparse


parser = argparse.ArgumentParser('ProNser')
parser.add_argument('-v' , '--verbose' , action='store_true',help="show full list of scripts with info (when using without -v shows short script names")
parser.add_argument('-t', '--type',help="search specific script categories or script names : discovery ,smb ...etc")
parser.add_argument('-i', '--info',help="show info on specific script : type script name")

args = vars(parser.parse_args())



foo = args['verbose']
bar = args['type']
cheese = args['info']

os.system('clear')


if (args['verbose'] == False)  and (args['type'] == None) and (args['info'] == None):

	
	
	os.system("cat /usr/share/nmap/scripts/script.db | awk {'print $5'}")

elif (args['verbose'] == True)  and (args['type'] == None) and (args['info'] == None):

	

	os.system("cat /usr/share/nmap/scripts/script.db | awk '{print $5,$8,$9,$10,$11,$12,$13,$14,$15,$16}'")


elif (args['verbose'] == False)  and (args['type'] != None) and (args['info'] == None):


	os.system("cat /usr/share/nmap/scripts/script.db |grep " + bar + " | awk '{print $5,$8,$9,$10,$11,$12,$13,$14,$15,$16}'" )


elif (args['verbose'] == False)  and (args['type'] == None) and (args['info'] != None):

	print "\n",cheese,"\n"

	print os.system("cat /usr/share/nmap/scripts/" + cheese + " | sed -n -e '/description/,/]/ p'")

	
	print "\n@Usage\n"
	with open('/usr/share/nmap/scripts/' + cheese) as file_iterator:
    		for line in file_iterator:
       			if "usage" in line:
            			print next(file_iterator)

	





